version: '3'
services:
  prometheus:
    image: prom/prometheus
    restart: on-failure
    network_mode: host
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:5.2.4
    network_mode: host
